services:
  - type: web
    name: flask-app
    env: python
    buildCommand: "pip install -r requirements_render.txt"
    startCommand: "gunicorn main:app --bind 0.0.0.0:10000"
    plan: free
    autoDeploy: true

    ignorePaths:
      - ..student_resources/**
      - .devcontainer/**
      - .vscode/**
      - requirements.txt
