services:
  - type: web
    name: flask-app
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn main:app --bind 0.0.0.0:10000 --timeout 120 --workers 1 --log-level debug --access-logfile - --error-logfile -"
    plan: free
    autoDeploy: true
    healthCheckPath: "/health"

    ignorePaths:
      - .student_resources/**
      - .devcontainer/**
      - .vscode/**

  - type: cron
    name: nightly-deployment
    env: python
    schedule: "0 14 * * *" # Midnight AEST (UTC+10) = 14:00 UTC
    buildCommand: "pip install requests"
    startCommand: "python deploy_script.py"
    plan: free
